### ISSUE TITLE
Not able to register plugin; nu 0.76.1

### ISSUE THREAD

**Issue by ryan-preble** [Euphrasiologist/nu_plugin_bio#8]
No idea what is going on, but when I attempt to type in the command `register nu_plugin_bio.exe`, this happens:
`register 'nu_plugin_bio.exe'' panicked at 'Error encoding response: PluginFailedToEncode("The pipe is being closed. (os error 232)")', C:\Users\Ryan\.cargo\registry\src\github.com-1ecc6299db9ec823\nu-plugin-0.74.0\src\plugin\mod.rs:250:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Error encoding response: PluginFailedToEncode("The pipe is being closed. (os error 232)")', C:\Users\Ryan\.cargo\registry\src\github.com-1ecc6299db9ec823\nu-plugin-0.74.0\src\plugin\mod.rs:250:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

Note that this does not happen when I press enter, it happens upon finishing typing the file name or when using tab completion.

**Comment by Euphrasiologist** [comment]
Hi, thanks for filing this! I think it was because I had only updated to 0.74.0. I've updated with nu 0.76.0, and this should work now. Please let me know!
